## Import numpy module

### For getting help with function, write the name of the function and question ``?`` mark:

In [1]:
import numpy as np
np?

In [2]:
# Create a numpy array from list
a = np.array([[1,2,3,4],[5,6,7,8]], dtype=np.float)
# Print dimensions
print(f"Shape of array a: {a.shape}")
# Print the total number of elements in array a
print(f"Size of array a: {a.size}")

Shape of array a: (2, 4)
Size of array a: 8


/tmp/ipykernel_39247/2577559895.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.array([[1,2,3,4],[5,6,7,8]], dtype=np.float)


## Other ways of creating numpy arrays

In [3]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b = np.linspace(0, np.pi, 20)
b

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [5]:
np.linspace

<function numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)>

In [6]:
c = np.ones(10)
c

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Indexing and slicing of arrays

In [7]:
# Simple indexing
mat = np.array([[1,2,3],[4,5,6]])

mat[0, 2]

3

In [8]:
mat[1,-2]

5

In [9]:
# Slicing every other element
a = np.arange(10)
a[1:7:2]

array([1, 3, 5])

In [10]:
# Slicing across dimensions
mat = np.zeros((4,4))
mat[1:3, 1:3] = 2.0
mat

array([[0., 0., 0., 0.],
       [0., 2., 2., 0.],
       [0., 2., 2., 0.],
       [0., 0., 0., 0.]])

## Views and copies of arrays

In [11]:
# Simple assignments creates references to arrays!
a = np.arange(10)
b = a # Reference, meaning changing values in b, changes values in a
b[0] = -500
a

array([-500,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [12]:
# True object copy
a = np.arange(10)
b = a.copy()
b[0] = -500
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Creating an array view
a = np.arange(10)
b = a[1:4] # Reference
b[:] = -500
a

array([   0, -500, -500, -500,    4,    5,    6,    7,    8,    9])

In [14]:
# Subarray copy
a = np.arange(10)
b = a[1:4].copy()
b[:] = -500
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Array manipulation

In [15]:
mat = np.array([[1,2,3], [4,5,6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
# Reshaping array
mat.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
# Flattening array
mat.ravel()

array([1, 2, 3, 4, 5, 6])

In [18]:
# Joining arrays
mat1 = np.array([[1, 2, 3], [4, 5, 6]])
mat2 = np.array([[7, 8, 9], [10, 11, 12]])

In [19]:
np.concatenate((mat1, mat2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [20]:
np.concatenate((mat1, mat2), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [21]:
# split array to N pieces
np.split(mat1, 3, axis=1)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

## Array operations 

Most operations for numpy arrays are done element-wise

``- + * / **``

In [22]:
a = np.array([1.0, 2.0, 3.0])

In [23]:
# Multiplying all elements with a constant
a * 2.0

array([2., 4., 6.])

In [24]:
# Adding a constant to all elements
a + 2.0

array([3., 4., 5.])

In [25]:
# Calculating square for all elements in array
a * a

array([1., 4., 9.])

Numpy has special functions which can 
work with array arguments

``sin, cos, exp, sqrt, log, ...``

In [26]:
a = np.linspace(-np.pi, np.pi, 8)
a

array([-3.14159265, -2.24399475, -1.34639685, -0.44879895,  0.44879895,
        1.34639685,  2.24399475,  3.14159265])

In [27]:
# Using python math module
import math
math.sin(a)

TypeError: only size-1 arrays can be converted to Python scalars

In [ ]:
# Using numpy.sin
np.sin(a)

Vectorized operations. 

Instead of using python for loops, which are slow, use numpy operations!

In [ ]:
arr = np.arange(10000)
dif = np.zeros(9999, dtype=np.int)
# Python for loop
for i in range(1, len(arr)):
    dif[i - 1] = arr[i] - arr[i - 1]

In [ ]:
arr = np.arange(10000)
dif = arr[1:] - arr[:-1]

## Broadcasting

If array shapes are different, the smaller array can be ``broadcasted`` into a larger shape

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.float)
a

In [ ]:
b = np.array([7, 11], dtype=np.float)
b

In [ ]:
a * b

## Advanced indexing

Numpy arrays can be indexed with other numpy arrays.

Results of such indexings are new numpy arrays.

In [ ]:
x = np.arange(10, 1, -1)
x

In [ ]:
x[np.array([3, 3, 1, 8])]

## *Boolean* mask arrays

In [ ]:
m = x > 7
m

## Masked arrays
* Sometimes datasets contain invalid data (faulty measurement, problem in simulation)
* Masked arrays provide a way to perform array operations  neglecting invalid data
* Masked array support is provided by numpy.ma module

In [ ]:
# Masked arrays can be created by 
# combining a regular numpy array and a 
# boolean mask

In [ ]:
import numpy.ma as ma
x = np.array([1, 2, 3, -1, 5])
m = x < 0
mx = ma.masked_array(x, mask=m)
mx

In [ ]:
x.mean()

In [ ]:
mx.mean()

## Random numbers

The module numpy.random provides several functions for constructing random arrays

* random: uniform random numbers
* normal: normal distribution
* poisson: Poisson distribution
* ...

In [ ]:
import numpy.random as rnd
rnd.random((2, 2))

In [ ]:
rnd.poisson(size=(2,2))

## Polynomials

Polynomial is defined by array of coefficients ``p``:
```python
p(x, N) = p[0] * x**(N-1)  + p[1] * x**(N-2)  + ... + p[N-1]
```

* Least square fitting: 
  * numpy.polyfit
* Evaluating polynomials: 
  * numpy.polyval
* Roots of polynomial:
  * numpy.roots

In [ ]:
x = np.linspace(-4, 4, 7)
y = x ** 2 + rnd.random(x.shape)
y

In [ ]:
p = np.polyfit(x, y, 2)
p

## Linear algebra

* Numpy can calculate matrix and vector products efficiently
  * dot, vdot, ...
* Eigenproblems
  * linalg.eig, linalg.eigvals, ...
* Linear systems and matrix inversion
  * linalg.solve, linalg.inv


In [ ]:
A = np.array(((2, 1), (1, 3)))
B = np.array(((-2, 4.2), (4.2, 6)))

In [ ]:
# Dot product between matrixes
C = np.dot(A, B)
C

In [ ]:
# Or use the @ operator (Python >= 3.6)
C = A @ B
C

In [ ]:
b = np.array((1,2))

In [ ]:
# Solve C x = b
result = np.linalg.solve(C, b)
result

In [ ]:
# Calculating different properties of a matrix
matrix = np.array(([1,2,3],[4,5,6],[7,8,9]))


# Using np.linalg.det function to calculated the determinant of a matrix
determinant = np.linalg.det(matrix)
print(f"Determinant of the matrix: {determinant}")

# Calculating the trace of the matrix
trace = np.trace(matrix)
print(f"Trace of the matrix: {trace}")

# Norm of the matrix
norm = np.linalg.norm(matrix)
print(f"Norm of the matrix: {norm}")



In [ ]:
# Creating simple sinuses
x = np.linspace(-np.pi, np.pi, 100)
y = np.sin(x)
z = np.sin(x + np.pi/4)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

# Plotting the data
plt.plot(x, y, label=r'$\sin(x)$')
plt.plot(x, z, label=r'$\sin(x + \frac{\pi}{4})$')
plt.legend()
plt.grid()
plt.show()